version: "3"

services:
  mysql-service:
    container_name: mysql-service
    build: ./mysql
    ports:
      - "7000:3306"
    volumes:
      - mysql:/mysql
    networks:
      - project
    restart: always
    command: --defaults-file=/mysql/conf/my.cnf
  redis-service:
    container_name: redis-service
    build: ./redis
    ports:
      - "8000:6379"
    volumes:
      - redis:/redis
    networks:
      - project
    restart: always
    command: /redis/conf/redis.conf
  mongo-service:
    container_name: mongo-service
    build: ./mongo
    ports:
      - "9000:27017"
    volumes:
      - mongo:/mongo
    networks:
      - project
    restart: always
    command: -f /mongo/conf/mongod.conf
  globalserver:
    image: globalserver:v1.4.2
    restart: always
    networks:
      - project
  userserver:
    image: userserver:v1.4.2
    ports:
      - 8080
      - 8081
      - 8082
    restart: always
    networks:
      - project

networks:
  project:
volumes:
  mysql:
  redis:
  mongo: