version: "3"

services:
  logserver:
    container_name: logserver
    image: logserver:v1.0.0
    ports:
      - 10000
      - 10001
      - 10002
    volumes:
      - log:/opt/logserver/log
    networks:
      - project
    restart: always
    stop_signal: SIGQUIT
  userserver:
    image: userserver:v1.0.1
    ports:
      - 8080
      - 8081
      - 8082
    networks:
      - project
    restart: always
    stop_signal: SIGQUIT
  globalserver:
    image: globalserver:v1.0.1
    networks:
      - project
    restart: always
    stop_signal: SIGQUIT

networks:
  project:
volumes:
  log: