version: "3"

services:
  registry:
    container_name: registry-service
    image: registry:v1.0.1
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - registry:/var/lib/registry
    restart: always
    networks:
      - project
  registry-ui:
    container_name: registry-ui-service
    image: joxit/docker-registry-ui:main-static
    ports:
      - "80:80"
    environment:
      URL: http://localhost:5000
      DELETE: "true"
    networks:
      - project

networks:
  project:
volumes:
  registry: