version: "3"

services:
  registry:
    container_name: registry-service
    image: registry:2
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - /home/frank/Desktop/k8s-learn/registry/conf/config.yml:/etc/docker/registry/config.yml
      - registry:/var/lib/registry
  registry-ui:
    container_name: registry-ui-service
    image: joxit/docker-registry-ui:main-static
    restart: always
    ports:
      - "80:80"
    environment:
      URL: "http://127.0.0.1:5000" # 在服务器上改成本机公网 ip
      DELETE_IMAGES: "true"

volumes:
  registry: