# 命名空间
apiVersion: v1    # 版本号
kind: Namespace   # 创建种类，此处是命名空间
metadata:         # 元数据
  name: web       # 命名

---

# 部署方式
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment    # 部署命名
  namespace: web          # 所属命名空间
spec:
  replicas: 6             # 副本数量，即同时存在达成模板描述状态的Pod
  template:               # 模板
    metadata:             # 元数据
      labels:             # 标签
        name: web-pod     # 命名
    spec:                 # 规格
      containers:         # Pod内容器描述
        - name: web-container               # 命名
          image: localhost:5000/web:v1.0.1  # 容器内镜像
  minReadySeconds: 5      # 新增Pod时，新的 Pods 已经就绪或者可用
  strategy:               # 升级策略
    type: RollingUpdate   # 升级类型，此处为滚动升级
    rollingUpdate:
      maxSurge: 1         # 指定可以创建的超出期望 Pod 个数的 Pod 数量
      maxUnavailable: 1   # 更新过程中不可用的 Pod 的个数上限
  selector:               # 选择器
    matchLabels:          # 匹配标签
      name: web-pod       # 匹配名称为 web 的容器

---
# 服务
apiVersion: v1
kind: Service
metadata:
  name: web-service       # 服务命名
  namespace: web          # 所属命名空间
spec:
  type: NodePort          # 类型
  selector:               # 选择器
    name: web-pod         # 选择所有名称为 web 的 Pods
  ports:                  # 端口组设定
    - protocol: TCP       # 端口协议
      port: 50453         # 服务绑定端口
      targetPort: 50453   # 服务绑定名称为 web 的 Pods的端口
      nodePort: 30000     # 服务绑定所在节点的端口
